# site properties and page defaults
title: Ubiquitous Cognitive Systems Group
subtitle: University Politehnica of Bucharest
description: The Ubiquitous Cognitive Systems Group (UCS) is a research group within the Faculty of Automatics and Control of the University Politehnica of Bucharest (UPB). The group is led by Conf. Dr. Eng. Ion-Emilian Radoi and focuses on the development of intelligent systems for the analysis of human behavior in unconstrained real world scenarios.
header: images/background.png
footer: images/background.png

# site social media and other links
links:
  email: emilian.radoi@upb.ro
  orcid:
  google-scholar: yjtWIf8AAAAJ
  # github: your-lab
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
